### PR TITLE
Forum dates requirement fix

### PR DESCRIPTION
**Pull request by Syxton**
Both dates are optional, but if one is given, both are required.

### CODE REVIEW

**Comment by Syxton** [comment]
This fixes an issue where Forum dates are showing and required when the forum is set to be assessed.  This caused dates to be saved on forums even if the user did not want them set.  However, a forum being assessed does not require the dates to be set.  It makes them optional, however if one date is set, the other also must be set.  This makes the dates optional but also has validation to make sure that both dates must be enabled to save any of them.

**Comment by timhunt** [comment]
I don't think adding validation is the right way to do this. The way it is supposed to work is that these fields should only appear if the other settings in the forum require them.

Therefore, I would have thought that the correct fix is to

* Change `if ($forum->assessed) {` to `if ($forum->assessed && $forum->ratingtime) {`
* Leave $isoptional as false for both report_editdates_date_setting.
* Remove the validation you added.

**Comment by Syxton** [comment]
@timhunt I actually tried that, but ratingtime isn't a real setting.

**Comment by timhunt** [comment]
OK, but what is the logic for how it is set? You should use the same logic here.

**Comment by Syxton** [comment]
course/moodleform_mod.php

> function data_preprocessing(&$default_values) {
     if (empty($default_values['scale'])) {
          $default_values['assessed'] = 0;
     }
     if (empty($default_values['assessed'])) {
           $default_values['ratingtime'] = 0;
     } else {
           $default_values['ratingtime'] = ($default_values['assesstimestart'] && $default_values['assesstimefinish']) ? 1 : 0;
     }
}

**Comment by Syxton** [comment]
I believe the validation is still required, ratingtime isn't true unless both times are not zero.  And if you hide the dates if this isn't true, then they can't be changed via the dates report.  But if you show them and require them, then when you save the dates report it will always be true (and you don't want that either).  So you really want to show the dates if assessed is true, but only save the dates if both dates are set (which will then make ratingtime true for the edit forum page).  I really think the validation method is the only way to make this work

**Comment by timhunt** [comment]
OK. I understand your logic now. Thank you for taking the time to explain. One final change request. Could you make the error message clearer? Perhaps "You must either set both the rating from and to dates, or neither."

**Comment by Syxton** [comment]
I can make that change, however I wasn't sure if any other mods might have a similar issue, so I kept the message vague so it could be reused.  Do you still want me to change it?

**Comment by timhunt** [comment]
Well, you could leave out the word 'rating'. I think it is worth making error messages as helpful as possible.

**Comment by Syxton** [comment]
"Both the to and from dates must be set or both must be disabled"  Sound good?

**Comment by Syxton** [comment]
Maybe better is "The to and from dates must both be set or both must be disabled"

**Comment by timhunt** [comment]
+1

**Comment by Syxton** [comment]
@timhunt Ok, change in the pull request has been made.  Thanks for our input

**Comment by timhunt** [comment]
I should have merged this before fixing issue #25. Anyway, merge conflicts sorted out now.

**Pull request closed without merging**
