### PR TITLE
Timeline Feature

### PR DESCRIPTION
**Pull request by Syxton**

### CODE REVIEW

**Comment by Syxton** [comment]
@timhunt Here is the timeline feature.

**Comment by Syxton** [comment]
rebased 11/21/2018

**Comment by Syxton** [comment]
@timhunt Sorry for that.  I've now fixed the css issue.  I am not sure how to do a behat test for this.  It doesn't have a lot of functionality, it is just a view.  That is why filters don't have behat tests.  Please advise.

**Comment by timhunt** [comment]
I would probably add some "And I should see ..." steps to the current scenario. And possibly add another scenario where the admin setting is turned off, and then there are some "And I should not see" checks".

Note: good test both verify the feature is working, but also help people understand how a feature is supposed to work.

**Comment by Syxton** [comment]
@timhunt Ok, behat tests done too.  Thanks for the input.

**Comment by Syxton** [comment]
I'll continue to keep this rebased just in case.
Also, I've attached a screenshot so people can see what this looks like.
timeline gui

**Comment by timhunt** [comment]
Yay! Finally this is merged. Sorry it took so long.

**Pull request closed without merging**
