### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by Syxton**
Includes pull requests #11,  #12, #13, #15
Also includes:
Fixes for turnitintooltwo when start dates are more that 1 year in the past
Fixes completion expected support
Adds GDPR compliance with privacy files

Please consider for merge into master.  Thanks!

### CODE REVIEW

**Comment by timhunt** [comment]
Thanks, and sorry I keep not getting time to look at these pull requests. Right now, I am about to go on holiday for the next week. We'll have to see what happens when I get back.

**Comment by Syxton** [comment]
@timhunt Thanks. I am working on preparing all our institutes plugins for a move to 3.5 this summer.  I'm just trying to make the process easy and fix as many bugs as I can find in the plugins we use.  Plus, anytime our faculty request some features/improvements I try to relay it back to the original author of the plugin.

**Comment by timhunt** [comment]
Thanks. That is great and appreciated.

What is not great is my inability to review all the pull requests I received. People trying to help deserve better than that!

**Comment by Syxton** [comment]
Just for documentation sake.  I found a bug with section names and links for restrict access.  They are now fixed in this request along with timeline icons.

**Comment by Syxton** [comment]
rebased with latest changes

**Comment by timhunt** [comment]
You went too soon with your rebase. I was still mergin the other requests.

I had a quick look through your commits, and they mostly look good, apart from the following issues:

1. If you are adding major new functionality, like the ability to edit availability dates, that really ought to have a Behat test to verify that it keeps working when we move to future Moodle versions. (Just a basic smoke-test is fine.)
2. If you have weird hackery like $first["time"] -= 86400; $last = end($data); $last["time"] += 86400; then that at the very least needs a comment to explain what is going on. Better would be to put that chunk of that date calculation into a helper function with a good name and PHP-doc comment, and unit tests to verify it does what is intended.
3. You probably saw the Travis build showing that your pull request has coding style issues, and other problems. E.g. https://travis-ci.org/moodleou/moodle-report_editdates/jobs/415920908.
4. I am not sure about the time-line view thing. Please could you use use this issue to submit all the changes except that, with the above issues fixed.
5. Then do a second pull request with the time-line changes, so I can consider them separately.

Now that I am on top of things, I should be able to look at your changes quite promptly. Thanks, Tim.

**Comment by Syxton** [comment]
@timhunt Yeah, sorry, I was trying to keep up as you manually merged the rest.  I'll try to get this to you soon.

**Comment by Syxton** [comment]
@timhunt Just a quick note.  Some of these changes overlap.  I can pretty easily remove the timeline feature, but giving you a timeline addition is difficult because some of the timeline hooks are inside areas that aren't currently available.  So the timeline feature would be incomplete.  The timeline feature will be branched from my other changes.

**Comment by timhunt** [comment]
Well the best thing would be to get all the other chagnes integrated into master first. Then worry about the timeline changes.

**Comment by Syxton** [comment]
@timhunt Ok, I think this part is ready to be looked at.

**Comment by Syxton** [comment]
@timhunt https://github.com/Syxton/moodle-report_editdates/tree/Timeline is the timeline branch, assuming this request is merged.  I made the timeline optional with a setting.

**Comment by timhunt** [comment]
OK, the Miscellaneous fixes are merged and I will close this pull request now.

Please open a new pull request for the timeline code, once it is ready.

I am afraid I found some bugs while reviewing the timeline code. I started fixing some of the problems while reviewing it, and the the changes I made, in case they are helpful, are https://github.com/moodleou/moodle-report_editdates/commit/ca0f4eabad9d73b9def52beee1a5537992c9b749. Be warned, I left in some debug code (print_object).

Note, I got rid of one of the admin settings, I think one setting is sufficient.

However, the bug is that if you have something with date 2674800 (31 January 1970 23:00:00 - no idea why I have that sitting in my testing course full of random junk!) then strcmp is not a valid way to sort integers.

Feel free to disagree with any of my proposed changes.

**Comment by Syxton** [comment]
@timhunt I like your changes.  Do you think it would be enough to simply cast variables in the strcmp()?

**Comment by timhunt** [comment]
No. I think you need to cast to int. I think it is now OK to make this PHP7-only. Therefore you can use $a <=> $b

**Pull request closed without merging**
